version: "3.8"

services:
    app-webapp:
        container_name: "app-webapp"
        image: "app-webapp:1.0.0"
        build:
            context: "."
            dockerfile: "dev/Dockerfile"
        ports:
            - "7860:7860"
        volumes:
            - "./app:/app"
