version: "3.8"

services:
    squarecode-app:
        container_name: "webapp-app"
        image: "squarecode-app:2.0.0"
        build:
            context: "."
            dockerfile: "dev/Dockerfile"
        ports:
            - "7860:7860"
        volumes:
            - "./app:/app"
