version: "3.8"

services:
    app-squarecode:
        container_name: "app-squarecode"
        image: "app-squarecode:1.0.0"
        build:
            context: "./app"
            dockerfile: "Dockerfile"
        ports:
            - "8999:8999"
        volumes:
            - "./app:/app"
